server.port=8090
spring.application.name=notification-service

# For local dev we won't actually send mail; configure SMTP in real env
spring.mail.host=localhost
spring.mail.port=25

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

