server.port=8761
spring.application.name=eureka-server

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Disable self-preservation for local dev convenience
eureka.server.enable-self-preservation=false

